steps:
  - id: 'initialize'
    name: 'us-central1-docker.pkg.dev/image-builder-dev/packer/packer'
    args:
    - 'init'
    - '.'
  - id: 'build-image'
    name: 'us-central1-docker.pkg.dev/image-builder-dev/packer/packer'
    args:
    - 'build'
    - '-only=build.*'
    - '.'
    env:
    - 'PKR_VAR_project_id=$PROJECT_ID'
    - 'PKR_VAR_image_name=${_BUILD_IMAGE_NAME}'
    - 'PKR_VAR_zone=${_ZONE}'
    - 'PKR_VAR_source_image_family=${_SOURCE_IMAGE_FAMILY}'
  - id: 'test-image'
    name: 'us-central1-docker.pkg.dev/image-builder-dev/packer/packer'
    args:
    - 'build'
    - '-only=test.*'
    - '.'
    env:
    - 'PKR_VAR_project_id=$PROJECT_ID'
    - 'PKR_VAR_image_name=${_BUILD_IMAGE_NAME}'
    - 'PKR_VAR_zone=${_ZONE}'
  - id: 'label-image-as-golden'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args:
    - 'gcloud'
    - 'compute'
    - 'images'
    - 'add-labels'
    - '${_BUILD_IMAGE_NAME}'
    - '--labels=golden=true'
substitutions:
    _SOURCE_IMAGE_FAMILY: default_yaml_source_image_family
    _ZONE: default_yaml_zone
    _IMAGE_NAME: default-yaml-image-name
    _BUILD_IMAGE_NAME: ${_IMAGE_NAME}-${SHORT_SHA}
options:
  logging: CLOUD_LOGGING_ONLY
