steps:
  - name: us-central1-docker.pkg.dev/image-builder-dev/packer/packer
    args:
    - 'init'
    - '.'
  - name: us-central1-docker.pkg.dev/image-builder-dev/packer/packer
    args:
    - 'build'
    - '-only=build.*'
    - '.'
    env:
    - 'PKR_VAR_project_id=$PROJECT_ID'
    - 'PKR_VAR_image_name=$_BUILD_IMAGE_NAME'
    - 'PKR_VAR_zone=${_ZONE}'
    - 'PKR_VAR_source_image_family=${_SOURCE_IMAGE_FAMILY}'
  - name: us-central1-docker.pkg.dev/image-builder-dev/packer/packer
    args:
    - 'build'
    - '-only=test.*'
    - '.'
    env:
    - 'PKR_VAR_project_id=$PROJECT_ID'
    - 'PKR_VAR_image_name=$_BUILD_IMAGE_NAME'
    - 'PKR_VAR_zone=${_ZONE}'
substitutions:
    _SOURCE_IMAGE_FAMILY: default_yaml_source_image_family
    _ZONE: default_yaml_zone
    _IMAGE_NAME: default_yaml_image_name
    _BUILD_IMAGE_NAME: ${_IMAGE_NAME}-${SHORT_SHA}
options:
  logging: CLOUD_LOGGING_ONLY
