steps:
  - name: us-central1-docker.pkg.dev/image-builder-dev/packer/packer
    args: ['init', '.']
  - name: us-central1-docker.pkg.dev/image-builder-dev/packer/packer
    args: ['build', '-only=build.*', '.']
  - name: us-central1-docker.pkg.dev/image-builder-dev/packer/packer
    args: ['build', '-only=test.*', '.']
options:
  logging: CLOUD_LOGGING_ONLY
